import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Signup extends javax.swing.JFrame {

    Connect DB = new Connect();
    public Signup() {
        initComponents();
        DB.main();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfEmail = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        lbLogin = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 760));
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setName("signupFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        tfEmail.setFont(new java.awt.Font("Circular Std Book", 0, 20)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(51, 51, 51));
        tfEmail.setMaximumSize(new java.awt.Dimension(500, 50));
        tfEmail.setMinimumSize(new java.awt.Dimension(500, 50));
        tfEmail.setPreferredSize(new java.awt.Dimension(500, 50));
        getContentPane().add(tfEmail);
        tfEmail.setBounds(40, 250, 480, 50);

        tfUsername.setFont(new java.awt.Font("Circular Std Book", 0, 20)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(51, 51, 51));
        tfUsername.setMaximumSize(new java.awt.Dimension(500, 50));
        tfUsername.setMinimumSize(new java.awt.Dimension(500, 50));
        tfUsername.setPreferredSize(new java.awt.Dimension(500, 50));
        getContentPane().add(tfUsername);
        tfUsername.setBounds(40, 350, 480, 50);

        pfPassword.setFont(new java.awt.Font("Circular Std Book", 0, 20)); // NOI18N
        pfPassword.setForeground(new java.awt.Color(51, 51, 51));
        pfPassword.setMaximumSize(new java.awt.Dimension(500, 50));
        pfPassword.setMinimumSize(new java.awt.Dimension(500, 50));
        pfPassword.setPreferredSize(new java.awt.Dimension(500, 50));
        getContentPane().add(pfPassword);
        pfPassword.setBounds(40, 460, 480, 50);

        btnSignup.setBackground(new java.awt.Color(37, 157, 212));
        btnSignup.setFont(new java.awt.Font("Circular Std Bold", 0, 20)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup);
        btnSignup.setBounds(40, 560, 480, 60);

        lbLogin.setFont(new java.awt.Font("Circular Std Book", 0, 20)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setText(" Login");
        lbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lbLogin);
        lbLogin.setBounds(320, 660, 80, 21);

        backgroundImage.setForeground(new java.awt.Color(255, 255, 255));
        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Sign Up.png"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String username = tfUsername.getText();
        String password = new String(pfPassword.getPassword());
        String email = tfEmail.getText();

        if (username.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "You must fill in all fields!");
            return;
        }

        String query = String.format("INSERT INTO otentikasi (username, password, email) VALUES ('%s', '%s', '%s')", username, password, email);
        try {
            int rowsAffected = DB.update(query);

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Signup successful!");
                Login loginFrame = new Login();
                loginFrame.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to signup. Please try again.");
            }
        } catch (Exception e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void lbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoginMouseClicked
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
