import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class TambahJurusan extends javax.swing.JFrame {

    Connect DB = new Connect();
    public TambahJurusan() {
        initComponents();
        Connect.main();
        tampilJurusanTable();
    }
    
    private void tampilJurusanTable() {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0); // Bersihkan tabel sebelum mengisi ulang

        try {
            String query = "SELECT * FROM jurusan";
            Statement stmt = DB.conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String kdJurusan = rs.getString("kdJurusan");
                String namaJurusan = rs.getString("namaJurusan");

                // Tambahkan baris baru ke tabel
                model.addRow(new Object[]{kdJurusan, namaJurusan});
            }
        } catch (SQLException e) {
            lbStatus.setText("Terjadi kesalahan: " + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        lbCariMhs = new javax.swing.JLabel();
        lbTambahMhs = new javax.swing.JLabel();
        lbEhMhs = new javax.swing.JLabel();
        lbTambahJur = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        tfkdJurusan = new javax.swing.JTextField();
        tfNamaJurusan = new javax.swing.JTextField();
        btnTambahJurusan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        backgroundImage = new javax.swing.JLabel();

        lb.setFont(new java.awt.Font("Circular Std Book", 0, 20)); // NOI18N
        lb.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setName("homeFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        lbCariMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCariMhsMouseClicked(evt);
            }
        });
        getContentPane().add(lbCariMhs);
        lbCariMhs.setBounds(21, 110, 200, 40);

        lbTambahMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTambahMhsMouseClicked(evt);
            }
        });
        getContentPane().add(lbTambahMhs);
        lbTambahMhs.setBounds(20, 180, 200, 40);

        lbEhMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEhMhsMouseClicked(evt);
            }
        });
        getContentPane().add(lbEhMhs);
        lbEhMhs.setBounds(20, 260, 200, 40);

        lbTambahJur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTambahJurMouseClicked(evt);
            }
        });
        getContentPane().add(lbTambahJur);
        lbTambahJur.setBounds(20, 330, 200, 40);

        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lbLogout);
        lbLogout.setBounds(20, 660, 200, 40);
        getContentPane().add(tfkdJurusan);
        tfkdJurusan.setBounds(440, 90, 40, 30);
        getContentPane().add(tfNamaJurusan);
        tfNamaJurusan.setBounds(440, 130, 250, 30);

        btnTambahJurusan.setBackground(new java.awt.Color(37, 157, 212));
        btnTambahJurusan.setFont(new java.awt.Font("Circular Std Book", 0, 14)); // NOI18N
        btnTambahJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahJurusan.setText("Tambah");
        btnTambahJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahJurusanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahJurusan);
        btnTambahJurusan.setBounds(520, 170, 90, 30);

        btnReset.setBackground(new java.awt.Color(104, 104, 104));
        btnReset.setFont(new java.awt.Font("Circular Std Book", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(620, 170, 70, 30);

        lbStatus.setFont(new java.awt.Font("Circular Std Book", 0, 14)); // NOI18N
        lbStatus.setText("Isi data, tidak boleh ada yang kosong");
        getContentPane().add(lbStatus);
        lbStatus.setBounds(440, 220, 460, 20);

        Table.setFont(new java.awt.Font("Circular Std Book", 0, 14)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Jurusan", "Nama Jurusan"
            }
        ));
        spTable.setViewportView(Table);

        getContentPane().add(spTable);
        spTable.setBounds(300, 280, 920, 350);

        backgroundImage.setForeground(new java.awt.Color(255, 255, 255));
        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Tambah Jurusan.png"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbTambahMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTambahMhsMouseClicked
        TambahMahasiswa tambahmhs = new TambahMahasiswa();
        tambahmhs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbTambahMhsMouseClicked

    private void lbEhMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEhMhsMouseClicked
        EditHapusMahasiswa ehmhs = new EditHapusMahasiswa();
        ehmhs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbEhMhsMouseClicked

    private void lbTambahJurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTambahJurMouseClicked
        
    }//GEN-LAST:event_lbTambahJurMouseClicked

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void btnTambahJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahJurusanActionPerformed
        // Ambil nilai dari tfkdJurusan dan tfNamaJurusan
        String kdJurusan = tfkdJurusan.getText();
        String namaJurusan = tfNamaJurusan.getText();

        // Cek apakah tfkdJurusan hanya berisi satu huruf besar
        if (kdJurusan.matches("[A-Z]{1}")) {
            try {
                // Query untuk INSERT data ke tabel jurusan
                String query = "INSERT INTO jurusan VALUES (?, ?)";
                PreparedStatement ps = DB.conn.prepareStatement(query);
                ps.setString(1, kdJurusan);
                ps.setString(2, namaJurusan);

                // Eksekusi query
                int rowsAffected = ps.executeUpdate();

                if (rowsAffected > 0) {
                    lbStatus.setText("Data berhasil ditambahkan.");
                    tfkdJurusan.setText("");
                    tfNamaJurusan.setText("");
                } else {
                    lbStatus.setText("Gagal menambahkan data.");
                }
                tampilJurusanTable();
            } catch (SQLException e) {
                lbStatus.setText("Terjadi kesalahan: " + e.getMessage());
            }
        } else {
            lbStatus.setText("Kode jurusan harus berisi satu huruf besar.");
        }
    }//GEN-LAST:event_btnTambahJurusanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        lbStatus.setText("Dibatalkan");
        tfkdJurusan.setText("");
        tfNamaJurusan.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void lbCariMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCariMhsMouseClicked
        CariMahasiswa carimhs = new CariMahasiswa();
        carimhs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbCariMhsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CariMahasiswa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambahJurusan;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbCariMhs;
    private javax.swing.JLabel lbEhMhs;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTambahJur;
    private javax.swing.JLabel lbTambahMhs;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTextField tfNamaJurusan;
    private javax.swing.JTextField tfkdJurusan;
    // End of variables declaration//GEN-END:variables
}
